# Generated by Django 6.0.1 on 2026-01-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('survey_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('location_code', models.CharField(blank=True, db_index=True, max_length=32)),
                ('location_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('dealer_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('activity', models.CharField(blank=True, db_index=True, max_length=32)),
                ('origin', models.CharField(blank=True, db_index=True, max_length=32)),
                ('result_status', models.CharField(blank=True, db_index=True, max_length=32)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=8)),
                ('date', models.DateTimeField(db_index=True)),
                ('final_date', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_phone', models.CharField(blank=True, max_length=40)),
                ('vin', models.CharField(blank=True, db_index=True, max_length=40)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=20)),
                ('model', models.CharField(blank=True, db_index=True, max_length=80)),
                ('overall_rating', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True)),
                ('experience_feedback', models.TextField(blank=True)),
                ('additional_feedback', models.TextField(blank=True)),
                ('anonymity', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('external_id', 'survey_id'), name='uniq_external_survey')],
            },
        ),
    ]
