# Generated by Django 6.0.1 on 2026-01-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='raw_schema_name',
            field=models.CharField(default='base_csv_v1', max_length=50),
        ),
    ]
